### ISSUE TITLE
What about Albino Flamingos

### ISSUE THREAD

**Issue by hilburn** [Vexatos/Flamingo#2]
![](http://fc00.deviantart.net/fs44/i/2013/059/6/c/albino_flamingo_fight__untrue__by_adrianblake-d206yj9.jpg)

**Comment by Vexatos** [comment]
That would be against everything this mod is about. Sorry.

**Comment by Vexatos** [comment]
Also, they are no Albinos, they are just white because they didn't ever get to eat the types of seafood that make their feathers pink.

**Comment by hilburn** [comment]
Actually not true - they can suffer from albinism just like all animals - interestingly though they can be albino, yet still pink as the pigment does not come from them. But their eyes will still be red

**Comment by Vexatos** [comment]
Indeed.

**Comment by hilburn** [comment]
So... where are my red-eyed flamingos?
