### ISSUE TITLE
Crash with Lil Tater Reloaded

### ISSUE THREAD

**Issue by Motschen** [Vexatos/Flamingo#29]
The mod crashes with Lil Tater Reloaded, here's the crash report:
https://hastebin.com/hisocofiti.cs

![tater](https://user-images.githubusercontent.com/49783724/82115793-41d21700-9765-11ea-9fd6-729da0fcf0d9.png)

**Comment by Vexatos** [comment]
Flamingo isn't exactly a complex mod, you should report it to them instead as I don't see how this would be this mod's fault.

**Comment by Yoghurt4C** [comment]
please close this `invalid` issue 🐛
