### ISSUE TITLE
ISBRH dat shit

### ISSUE THREAD

**Issue by hilburn** [Vexatos/Flamingo#3]
Tile Entities are unnecessary,
Flamingos could easily be converted to non-TE blocks with an ISBRH renderer to reduce render load

**Comment by Vexatos** [comment]
If I knew how to, I would.

**Comment by iTitus** [comment]
lol

**Comment by iTitus** [comment]
Tweak the shit out of this gigantic mod!

**Comment by Vexatos** [comment]
Exactly.

**Comment by copygirl** [comment]
You do know they animate when you hit them, right?

**Comment by hilburn** [comment]
I do - but a ISBRH can handle animated blocks no worries

**Comment by copygirl** [comment]
Unsure if that's the case, but if so, there'd be the same render load regardless, and where would I save the data related to rendering the block? (Whether it's currently animated and where it is in its animation.)

**Comment by hilburn** [comment]
It would not save anything in particular when wiggling, but when not wiggling it would not trigger render updates every tick
The wiggle data could still be stored in a TE - you are passed the world and x, y, z coords in the ISBRH so you can easily access the tile

**Comment by copygirl** [comment]
And how would you use the ISBRH to do animations? Wouldn't that need to rerender the chunk?

**Comment by hilburn** [comment]
You could look at Buildcraft pipes which animate item movement through them while being ISBRH - there are a couple of other examples of animated blocks not using a TESR but I don't have them to hand

**Comment by copygirl** [comment]
That's a static and an additional moving part. Not an object that's sometimes static and sometimes moving.

**Comment by hilburn** [comment]
Like I said, it was an example, there are others
Marking a block for a render update doesn't re-render the entire chunk - rather a 16x16x16. Now some proportion of blocks around a flamingo is going to be air - I'd say close to 50% but let's say 30% as a worst case.
Compare that to a TESR - which always re-renders it's contents regardless of whether you can see it or it has updated: Average player at 30fps, that's 30 renders per second. Even the most ardent flamingo enthusiast is not going to be wiggling more than 1% of the time. 16\*16\*16\*0.7\*0.01 = average of 28 renders/s, the majority of which are cheaper computationally than TESR model renders and that's absolute worst case - I reckon regular use would be <10

**Comment by copygirl** [comment]
These 16x16x16 render regions are also called chunks, hence "chunk updates". Chunk updates are significantly more expensive than straight up rendering them, requiring creating new display lists and using the tesselator and block rendering methods to compile them again.

Yes, if Flamingos were static, it may speed up rendering a bit. Does it matter? Not until you place thousands of them in your world. I'd be more worried about chests. Would it make sense to go through all this work (writing transformation functions for rotating vectors of the default model, etc...) just to maybe get a absolutely tiny performance boost? No.

Read up on "premature optimization" if you want.

**Comment by hilburn** [comment]
If Flamingos were static it would definitely speed up rendering a bit, as they are not, it would in 99.9% of cases.
As for the incredible effort of calling `glRotate(0, a, 0);` in a render function I will refrain from commenting on that.
Premature optimization is a thoroughly inappropriate phrase to be throwing around at this juncture - the codebase hasn't changed in 9 months and thus can reasonably be considered finished. Premature optimization refers to work done in the development - and a caution against spending time optimizing non-critical pathways. For a completed and non functional, aesthetic mod, you are working on the only pathway that actually matters and not at the expense of developing other features.
Actually an interesting middle ground would be to have it only create the tile entity when it is hit, use the TESR for the wiggle and then remove the TE as it returns to rest, using an ISBRH to massively reduce render load during the 99%+ of time that a flamingo is not wiggling and then the TESR prevents the necessity for a bunch of render updates. Further you might even be able to run the TE client side only which means you'd be saving space and performance on the server side - though I am not sure MC wouldn't cull it.

**Comment by Vexatos** [comment]
How in the world would you have a Flamingo and not wiggle it? I cannot comprehend the meaning of your statement...

**Comment by hilburn** [comment]
I never suggested no having wiggling flamingos - but @copygirl said " if Flamingos were static, it may speed up rendering a bit" - which is not correct - if they were static then using an ISBRH would definitely speed up rendering

**Comment by copygirl** [comment]
\**puts on tinfoil hat**

I'm not sure if this is serious anymore or not. I'll be over in that corner silently banging my head against the wall. Don't worry though, this is a reinforced tinfoil hat.

**Comment by hilburn** [comment]
This hasn't been particularly serious since the first comment - I only made the issue to annoy @Vexatos

**Comment by asiekierka** [comment]
>ISBRH
>1.8.8

**Comment by Vexatos** [comment]
Fixed via #7.
