### ISSUE TITLE
Koalas?

### ISSUE THREAD

**Issue by hilburn** [Vexatos/Flamingo#4]
I think it would be great if this mod added koalas - they go so naturally with Flamingos
Here's a baby koala being cared for by a Flamingo - I assume it's mother is having a nap or had chlamydia and died
![koala](https://cloud.githubusercontent.com/assets/8307858/8094496/63dc3e9e-0fbf-11e5-9fc3-185d36a74008.png)

**Comment by way2muchnoise** [comment]
![](http://cicexpress.ca/wp-content/uploads/2014/11/Approved.jpeg)

**Comment by Vexatos** [comment]
Hmmm... How to say it in the kindest way possible...
